[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
fs_permissions = [
  { access = "read", path = "./test/fixtures" }
]

remappings = [
  "@gluwa/asc-contracts/=node_modules/@gluwa/asc-contracts/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
